apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bib-operator.fullname" . }}
  labels:
    {{- include "bib-operator.labels" . | nindent 4 }}
rules:
  # leader election rules
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  # manager rules
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - create
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - bib.cluster.x-k8s.io
    resources:
    - imagebuilds
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - bib.cluster.x-k8s.io
    resources:
    - imagebuilds/finalizers
    verbs:
    - update
  - apiGroups:
    - bib.cluster.x-k8s.io
    resources:
    - imagebuilds/status
    verbs:
    - get
    - patch
    - update
  # metrics auth rules
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bib-operator.fullname" . }}
  labels:
    {{- include "bib-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bib-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bib-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
