# This rule is not used by the project bib-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the bib.cluster.x-k8s.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bib-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagebuild-editor-role
rules:
- apiGroups:
  - bib.cluster.x-k8s.io
  resources:
  - imagebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bib.cluster.x-k8s.io
  resources:
  - imagebuilds/status
  verbs:
  - get
